# Generated automatically from Makefile.config.in by configure.

GWML_RELEASE=3.01
GWML_VERSION=1.00
IMLIB_COBJS=
IMLIB_CFLAGS=
IMLIB_CLINK=
ESD_COBJS=
ESD_CFLAGS=
ESD_CLINK=
OCAMLLIB=/usr/local/lib/cdk-3.04/lib/ocaml-3.04
BINDIR=/usr/local/lib/cdk-3.04/bin
LIBDIR=/usr/local/lib/cdk-3.04/lib
